# This exercise code is generated by GPT. With the following prompt:

# Problem Statements:
# Please come up with three vectors in \(\mathbb{R}^4\) that are not linearly independent as a set,
# but each pair of vectors within the set should be linearly independent.
# Print each vector in LaTeX format for the student to validate.
#
# User Input:
# Read the student's input, expecting a list of three vectors.
# Convert the input to sympy matrices.
#
# Validation:
# Ensure that there are exactly three vectors provided by the student.
# Verify that each vector is in \(\mathbb{R}^4\) by checking if each matrix has 4 rows and 1 column.
# Verify if the three vectors as a set are not linearly independent.
# Check that each pair of vectors within the set is linearly independent.
#
# Feedback:
# If the number of vectors is not three, raise an exception with an appropriate message.
# If any vector is not in \(\mathbb{R}^4\), raise an exception with an appropriate message.
# If the three vectors as a set are linearly independent, raise an exception with an appropriate message.
# If any pair of vectors is not linearly independent, raise an exception with an appropriate message.
# If all checks pass, print a confirmation message that the student's vectors are correct.
#
# Cautions:
# Always include necessary packages: import json, from sympy import Matrix, latex.
# Ensure to use "$$ {latex(...)} $$" for MathJax to correctly display mathematical expressions.
# Use double braces {{...}} to avoid conflicts with Python's string formatting.

import json
from sympy import Matrix, latex

# Print the problem statement
print("Please come up with three vectors in $$\\mathbb{{R}}^4$$ that are not linearly independent as a set,")
print("but each pair of vectors within the set should be linearly independent.")

# Read the student's input (expecting a list of three vectors)
X = json.loads(input()) #matrix

# Convert the input to sympy matrices
vectors = [Matrix(v) for v in X]

# Ensure that there are exactly three vectors
if len(vectors) != 3:
    raise Exception("You must provide exactly three vectors.")

# Verify that each vector is in \(\mathbb{R}^4\) by checking if each matrix has 4 rows and 1 column
for vec in vectors:
    if vec.rows != 4 or vec.cols != 1:
        raise Exception(f"Each vector must be a column vector in $$\\mathbb{{R}}^4$$, but the vector $$ {latex(vec)} $$ does not meet this requirement.")

# Combine the vectors into a matrix
combined_matrix = Matrix.hstack(*vectors)

# Verify if the three vectors as a set are not linearly independent
if combined_matrix.rank() == 3:
    raise Exception("The three vectors provided are linearly independent as a set, which is incorrect.")

# Check that each pair of vectors within the set is linearly independent
for i in range(3):
    for j in range(i + 1, 3):
        pair_matrix = Matrix.hstack(vectors[i], vectors[j])
        if pair_matrix.rank() != 2:
            raise Exception(f"The vectors $$ {latex(vectors[i])} $$ and $$ {latex(vectors[j])} $$ are not linearly independent as a pair.")

print("Your suggested vectors are correct.")

